### ISSUE TITLE
I don't see the download links of the public dataset in the paper

### ISSUE THREAD

**Issue by baltam** [LujianYao/FoSp#1]
Awesome work!Thank you for providing such excellent work! I have some question I would like to consult with you.

- According to the paper, SmokeSeg are publicly available at github, but I don't see the download links of the public dataset. Just wanted to point out that the script provided in the GitLab project for the FIgLib dataset only includes annotation data for the bounding boxes of the targets. It seems like there's no annotation for the contours available at the moment. I wanted to inquire if there's a possibility to get some contour annotation data for the smoke included in the dataset. It would be incredibly appreciated as it would enhance our research significantly. It would be really helpful for a more detailed analysis. Thanks!

- According to the paper, the complete code publicly available at github, but I don't see the download links of the code. If it does not violate the terms of specific funding agency or other restrictions, would you be interested in making the code available to other researchers, so that researchers could compare their work, Thanks!

**Comment by LujianYao** [comment]
Hello, thank you for your attention to our work. We just updated the main code.
